import type { Metadata } from "next";
import "./globals.css";
import ToastNotification from "@/src/components/ToastNotification";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="h-dvh w-dvw flex bg-segundo">
        {children}
        <ToastNotification />
      </body>
    </html>
  );
}
